/-
  Standard syntactic homeomorphic embedding boundary.

  Relation: the duplicating SchemaKernel Step relation and the copy-removed
    SANS Step control.
  Closure: a recursive root counterexample suffices to refute orientation of
    full contextual Step by the strict embedding order.
  Property: for the standard syntactic homeomorphic embedding generated by
    diving and same-symbol coupling, the recursive right side does not embed
    in the left side on either system. Hence strict homeomorphic embedding
    cannot orient the recursive rule. The SANS theorem shows this particular
    failure is not caused by duplication.
  Trust: Mathlib and existing benchmark modules only; no proof shortcuts or
    new axioms. Open remainder: variable-wildcard, substitution-quotiented,
    and other generalized embedding relations are not identified with this
    standard syntactic relation.
-/
import Mathlib.Tactic
import KO7Benchmark.SchemaTests.SchemaKernel
import KO7Benchmark.SANSTests.SANSKernel
import KO7Benchmark.ScoringAnchors.MeasureFailures

set_option autoImplicit false

namespace KO7Benchmark.ScoringAnchors.EmbeddingBoundary

namespace Schema

open KO7Benchmark.SchemaTests
open SKTerm
open KO7Benchmark.ScoringAnchors.MeasureFailures

/-- Standard syntactic homeomorphic embedding, with Emb a b meaning that
a embeds into b. Variables are ordinary nullary syntax symbols. -/
inductive Emb : SKTerm → SKTerm → Prop
  | refl (t : SKTerm) : Emb t t
  | dive_s {a t : SKTerm} : Emb a t → Emb a (s t)
  | dive_g_left {a l r : SKTerm} : Emb a l → Emb a (g l r)
  | dive_g_right {a l r : SKTerm} : Emb a r → Emb a (g l r)
  | dive_f_first {a x y n : SKTerm} : Emb a x → Emb a (f x y n)
  | dive_f_second {a x y n : SKTerm} : Emb a y → Emb a (f x y n)
  | dive_f_third {a x y n : SKTerm} : Emb a n → Emb a (f x y n)
  | couple_s {a b : SKTerm} : Emb a b → Emb (s a) (s b)
  | couple_g {a₁ a₂ b₁ b₂ : SKTerm} :
      Emb a₁ b₁ → Emb a₂ b₂ → Emb (g a₁ a₂) (g b₁ b₂)
  | couple_f {a₁ a₂ a₃ b₁ b₂ b₃ : SKTerm} :
      Emb a₁ b₁ → Emb a₂ b₂ → Emb a₃ b₃ →
        Emb (f a₁ a₂ a₃) (f b₁ b₂ b₃)

theorem size_le_of_emb {a b : SKTerm} (h : Emb a b) : size a ≤ size b := by
  induction h with
  | refl t => exact Nat.le_refl _
  | dive_s h ih =>
      simp only [size_s]
      omega
  | dive_g_left h ih =>
      simp only [size_g]
      omega
  | dive_g_right h ih =>
      simp only [size_g]
      omega
  | dive_f_first h ih =>
      simp only [size_f]
      omega
  | dive_f_second h ih =>
      simp only [size_f]
      omega
  | dive_f_third h ih =>
      simp only [size_f]
      omega
  | couple_s h ih =>
      simp only [size_s]
      omega
  | couple_g h₁ h₂ ih₁ ih₂ =>
      simp only [size_g]
      omega
  | couple_f h₁ h₂ h₃ ih₁ ih₂ ih₃ =>
      simp only [size_f]
      omega

theorem recursive_rhs_not_embedded (x y n : SKTerm) :
    ¬ Emb (g y (f x y n)) (f x y (s n)) := by
  intro h
  have hle := size_le_of_emb h
  have hlt := size_increases x y n
  omega

def StrictEmb (a b : SKTerm) : Prop :=
  Emb b a ∧ ¬ Emb a b

theorem no_strict_embedding_orients_recursive_root :
    ¬ (∀ x y n : SKTerm, StrictEmb (f x y (s n)) (g y (f x y n))) := by
  intro h
  exact recursive_rhs_not_embedded z z z (h z z z).1

theorem no_strict_embedding_orients_step :
    ¬ (∀ {a b : SKTerm}, Step a b → StrictEmb a b) := by
  intro h
  have hs := h (Step.root (RootStep.succ z z z))
  exact recursive_rhs_not_embedded z z z hs.1

end Schema

namespace SANS

open KO7Benchmark.SANSTests
open SANSTerm

/-- Standard syntactic homeomorphic embedding on the SANS signature. -/
inductive Emb : SANSTerm → SANSTerm → Prop
  | refl (t : SANSTerm) : Emb t t
  | dive_s {a t : SANSTerm} : Emb a t → Emb a (s t)
  | dive_g {a t : SANSTerm} : Emb a t → Emb a (g t)
  | dive_f_first {a x y n : SANSTerm} : Emb a x → Emb a (f x y n)
  | dive_f_second {a x y n : SANSTerm} : Emb a y → Emb a (f x y n)
  | dive_f_third {a x y n : SANSTerm} : Emb a n → Emb a (f x y n)
  | couple_s {a b : SANSTerm} : Emb a b → Emb (s a) (s b)
  | couple_g {a b : SANSTerm} : Emb a b → Emb (g a) (g b)
  | couple_f {a₁ a₂ a₃ b₁ b₂ b₃ : SANSTerm} :
      Emb a₁ b₁ → Emb a₂ b₂ → Emb a₃ b₃ →
        Emb (f a₁ a₂ a₃) (f b₁ b₂ b₃)

/-- A positive symbol-weight rank. Giving G weight two separates the SANS
recursive source and target while remaining monotone under standard embedding. -/
def rank : SANSTerm → Nat
  | .var _ => 1
  | .z => 1
  | .s t => rank t + 1
  | .g t => rank t + 2
  | .f x y n => rank x + rank y + rank n + 1

theorem rank_pos (t : SANSTerm) : 0 < rank t := by
  induction t <;> simp [rank, *]

theorem rank_le_of_emb {a b : SANSTerm} (h : Emb a b) : rank a ≤ rank b := by
  induction h with
  | refl t => exact Nat.le_refl _
  | dive_s h ih =>
      simp only [rank]
      omega
  | dive_g h ih =>
      simp only [rank]
      omega
  | dive_f_first h ih =>
      simp only [rank]
      omega
  | dive_f_second h ih =>
      simp only [rank]
      omega
  | dive_f_third h ih =>
      simp only [rank]
      omega
  | couple_s h ih =>
      simp only [rank]
      omega
  | couple_g h ih =>
      simp only [rank]
      omega
  | couple_f h₁ h₂ h₃ ih₁ ih₂ ih₃ =>
      simp only [rank]
      omega

theorem recursive_target_rank_gt (x y n : SANSTerm) :
    rank (f x y (s n)) < rank (g (f x y n)) := by
  simp [rank]
  omega

theorem recursive_rhs_not_embedded (x y n : SANSTerm) :
    ¬ Emb (g (f x y n)) (f x y (s n)) := by
  intro h
  have hle := rank_le_of_emb h
  have hlt := recursive_target_rank_gt x y n
  omega

def StrictEmb (a b : SANSTerm) : Prop :=
  Emb b a ∧ ¬ Emb a b

theorem no_strict_embedding_orients_recursive_root :
    ¬ (∀ x y n : SANSTerm,
      StrictEmb (f x y (s n)) (g (f x y n))) := by
  intro h
  exact recursive_rhs_not_embedded z z z (h z z z).1

theorem no_strict_embedding_orients_step :
    ¬ (∀ {a b : SANSTerm}, Step a b → StrictEmb a b) := by
  intro h
  have hs := h (Step.root (RootStep.succ z z z))
  exact recursive_rhs_not_embedded z z z hs.1

end SANS

end KO7Benchmark.ScoringAnchors.EmbeddingBoundary
