"""Seed blank extraction rows for window-arm sessions that are on disk but absent
from an arm's extraction CSVs.

Why this exists: the window-arm surfaces use the flat
`results/<arm>/extraction/<PREFIX>_r<N>_extractor_0{1,2}.csv` layout, which
`sync_extraction_sessions.py` does not cover (that script targets the July-corpus
`3.extraction/batches/...` layout). When an arm's roster grows after its extraction
files were first built, the new sessions have nowhere to be transcribed and the whole
downstream chain (dual extraction -> gate -> adjudication) silently under-covers.

What it does: appends one BLANK row per missing session to the LEDGER and to BOTH
extractor CSVs, preserving each file's exact header and column count. Extraction agents
then fill those rows exactly as before.

What it deliberately does NOT touch:
  * response.txt / session.json      (session files are never edited)
  * <PREFIX>_r<N>.csv                (the GATED output -- regenerated by
                                      r5_construction_gate.py, never hand-edited)
  * any already-present row          (idempotent: only genuinely missing slugs are added)

    python scripts/seed_arm_extraction_rows.py                 # dry run, all arms
    python scripts/seed_arm_extraction_rows.py --apply
    python scripts/seed_arm_extraction_rows.py --arm tools --apply
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from pathlib import Path

csv.field_size_limit(2**31 - 1)
ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"

ARMS = {
    "tools":   {"surface": "test-01-tools-arm-tests",   "prefix": "TEST01_TOOLS",    "round": 4},
    "nonce":   {"surface": "schema-a-nonce-arm-tests",  "prefix": "SCHEMA_A_NONCE",  "round": 5},
    "context": {"surface": "test-01-context-arm-tests", "prefix": "TEST01_CONTEXT",  "round": 4},
}


def read_csv(path: Path) -> tuple[list[str], list[list[str]]]:
    with path.open(encoding="utf-8-sig", newline="") as fh:
        rows = list(csv.reader(fh))
    return (rows[0], rows[1:]) if rows else ([], [])


def slug_col(header: list[str]) -> int:
    for i, c in enumerate(header):
        if "slug" in c.lower():
            return i
    return 0


def session_meta(sessions_dir: Path, slug: str) -> dict:
    mf = sessions_dir / slug / "session.json"
    try:
        return json.loads(mf.read_text(encoding="utf-8"))
    except Exception:
        return {}


def seed_arm(key: str, apply: bool) -> int:
    cfg = ARMS[key]
    surface = RESULTS / cfg["surface"]
    exdir, sessions_dir = surface / "extraction", surface / "test-sessions"
    if not exdir.is_dir() or not sessions_dir.is_dir():
        print(f"  {key}: surface not found, skipped")
        return 0

    on_disk = sorted(d.name for d in sessions_dir.iterdir() if d.is_dir())
    targets = [exdir / f"{cfg['prefix']}_LEDGER.csv",
               exdir / f"{cfg['prefix']}_r{cfg['round']}_extractor_01.csv",
               exdir / f"{cfg['prefix']}_r{cfg['round']}_extractor_02.csv"]

    print(f"\n=== ARM {key}  ({len(on_disk)} sessions on disk) ===")
    total_added = 0
    for path in targets:
        if not path.exists():
            print(f"  {path.name:38s} MISSING FILE -- skipped (create it before seeding)")
            continue
        header, rows = read_csv(path)
        i = slug_col(header)
        have = {r[i].strip() for r in rows if len(r) > i and r[i].strip()}
        missing = [s for s in on_disk if s not in have]
        if not missing:
            print(f"  {path.name:38s} {len(rows):4d} rows  already complete")
            continue

        new_rows = []
        for slug in missing:
            row = [""] * len(header)
            row[i] = slug
            if path.name.endswith("_LEDGER.csv"):          # ledger carries identity columns
                m = session_meta(sessions_dir, slug)
                for j, col in enumerate(header):
                    c = col.strip().lower()
                    if c == "model":
                        row[j] = m.get("model_slug", "")
                    elif c == "provider":
                        row[j] = m.get("provider") or ""
                    elif c == "variant":
                        row[j] = "fruit" if m.get("variant_suffix") == "-fruit" else "kernel"
            new_rows.append(row)

        print(f"  {path.name:38s} {len(rows):4d} rows  +{len(new_rows)} blank -> {len(rows)+len(new_rows)}")
        total_added += len(new_rows)
        if apply:
            # append only; never rewrite existing bytes
            with path.open("a", encoding="utf-8", newline="") as fh:
                csv.writer(fh, lineterminator="\r\n").writerows(new_rows)

    gated = exdir / f"{cfg['prefix']}_r{cfg['round']}.csv"
    if gated.exists():
        _, grows = read_csv(gated)
        print(f"  {gated.name:38s} {len(grows):4d} rows  GATED - left untouched "
              f"(re-run r5_construction_gate.py after extraction)")
    return total_added


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--arm", choices=[*ARMS, "all"], default="all")
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    keys = list(ARMS) if a.arm == "all" else [a.arm]
    total = sum(seed_arm(k, a.apply) for k in keys)
    print(f"\n{'APPLIED' if a.apply else 'DRY RUN'}: {total} blank row(s) "
          f"{'appended' if a.apply else 'would be appended'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
